#!/usr/bin/env python3
"""Assemble + execute carry_eth.ipynb (system Python with nbformat/nbclient; cells run in the repo venv).

    C:/Python/Python313/python.exe studies/notebooks/carry_eth_2026_09/build_notebook.py

The cells render results/ written by run_eth.py; they do not recompute. Re-run run_eth.py first.
"""
from __future__ import annotations

import json
import os
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[2]
VENV_PY = ROOT / "venv" / "Scripts" / "python.exe"
NB_PATH = HERE / "carry_eth.ipynb"


def register_temp_kernel() -> str:
    tmp = tempfile.mkdtemp(prefix="carry_eth_kernel_")
    kd = Path(tmp) / "kernels" / "p300venv"
    kd.mkdir(parents=True)
    (kd / "kernel.json").write_text(json.dumps({
        "argv": [str(VENV_PY), "-m", "ipykernel_launcher", "-f", "{connection_file}"],
        "display_name": "p300 venv", "language": "python"}), encoding="utf-8")
    prev = os.environ.get("JUPYTER_PATH")
    os.environ["JUPYTER_PATH"] = tmp + (os.pathsep + prev if prev else "")
    return "p300venv"


HEADER = """\
# CARRY on ETH 2026-09 (AUDIT of the shipped rule on a second asset)

Pre-registration: [README.md](README.md) (frozen before any run). Write-up: [findings.md](findings.md).
The shipped CUM-30D carry rule on Binance ETHUSDT settlement prints, net of 0.24 % per toggle, with the C2 rule
simulator imported unchanged; the combined BTC + ETH book against BTC alone. Re-run: `run_eth.py`.
"""

LOAD = """\
import json, pandas as pd
from pathlib import Path
R = Path('results')
J = json.loads((R / 'carry_eth.json').read_text(encoding='utf-8'))
print('generated by:', J['env'])
print('C0 gate:', J['c0_gate'])
print('parity vs the BTC study:', J['parity'])
"""

RULES = """\
for name in ('eth', 'btc'):
    r = J[name]
    print(f"{name.upper()} — {r['eval_span'][0]} .. {r['eval_span'][1]} ({r['years']:.2f} y, {r['n_prints']} prints)")
    display(pd.DataFrame(r['rules']).T.round(3))
"""

YEARS = """\
pdf = pd.read_csv(R / 'per_year.csv')
for sym in ('ETHUSDT', 'BTCUSDT'):
    print(sym, 'net %/yr by year')
    display(pdf[pdf.symbol == sym].pivot_table(index='rule', columns='year', values='net_ann_pct').round(2))
print('ETH era split:', json.dumps(J['eth']['era'], indent=1))
print('ETH tail stress:', json.dumps(J['eth']['tail_stress'], indent=1))
print('ETH CUM30D bootstrap vs zero:', J['eth']['bootstrap_cum30d_vs_zero'])
"""

COMBINED = """\
print('combined book:', json.dumps(J['combined'], indent=1))
cd = pd.read_csv(R / 'combined_daily.csv', index_col=0)
cum = (cd.cumsum() * 100).rename(columns={'btc_net': 'BTC CUM30D', 'eth_net': 'ETH CUM30D'})
cum['equal weight'] = (0.5 * cd.btc_net + 0.5 * cd.eth_net).cumsum() * 100
ax = cum.plot(figsize=(10, 4), title='cumulative net funding, % of capital')
ax.set_ylabel('%')
"""

DECISION = """\
print('DECISION:', json.dumps(J['decision'], indent=1))
"""


def main() -> None:
    import nbformat
    from nbclient import NotebookClient
    from nbformat.v4 import new_code_cell, new_markdown_cell, new_notebook

    kernel = register_temp_kernel()
    nb = new_notebook(metadata={"kernelspec": {"name": kernel, "display_name": "p300 venv", "language": "python"}})
    nb.cells = [new_markdown_cell(HEADER),
                new_markdown_cell("## Gates — C0 (prints = prod.db settlement rows) and parity with the BTC study"),
                new_code_cell(LOAD),
                new_markdown_cell("## Rules on ETH and on BTC (the references are the BTC study's anchors)"),
                new_code_cell(RULES),
                new_markdown_cell("## Per year, era, tail stress, bootstrap"),
                new_code_cell(YEARS),
                new_markdown_cell("## The combined book — the breadth test"),
                new_code_cell(COMBINED),
                new_markdown_cell("## Decision (rule fixed in README.md before the run)"),
                new_code_cell(DECISION)]
    client = NotebookClient(nb, timeout=600, kernel_name=kernel, resources={"metadata": {"path": str(HERE)}})
    client.execute()
    nbformat.write(nb, NB_PATH)
    print("executed and wrote", NB_PATH)


if __name__ == "__main__":
    main()
